#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use App\Commands\SampleCommand;

$application = new Application();

// ... register commands
$application->add(new SampleCommand());

$application->run();